### ISSUE TITLE
Resulting hexagram

### ISSUE THREAD

**Issue by ghost** [digitalillusion/org-digitalillusion-droid-iching#1]
I do not see that there is a place to see the resulting hexagram after getting the changing lines. Am I missing this?

**Comment by digitalillusion** [comment]
First, make sure that you got a changing line. They are market with a X or an O upon creation of the hexagram
Then, you will have 3 tabs above when consulting the reading:
![image](https://user-images.githubusercontent.com/94325/111594784-c9484680-87cb-11eb-8169-a378537a0266.png)
The transformed hexagram tab gives the inforrmation that you want.

**Comment by digitalillusion** [comment]
fixed in 1.11.0
