### ISSUE TITLE
How do you export or back up?

### ISSUE THREAD

**Issue by Inclement9** [digitalillusion/org-digitalillusion-droid-iching#2]
I'd like to be able to share to Dropbox, since I have Dropbox installed on my tablet and have done this successfully with other apps. But some other means of exporting or backing up would probably be fine, too.

The only thing I've managed to think of is to take screenshots and save them to the cloud. But you need two screenshots for every reading:
(a) the history screen, in order to preserve the reading's time and date
(b) the actual reading screen (from the "Changing Lines" tab) to save the actual casting.

That is obviously very laborious.

I emailed you about this back in July at the address given in the app, but haven't heard back.

Thank you for any help...

**Comment by digitalillusion** [comment]
Hi,
please make sure that in the settings you have selected Content to share: Reading. This will export the whole reading, question included, when you use the share feature. 
The share feature produces some HTML content; I have no control on how the receiver (Dropbox app in your case) handle this content. If it doesn't work directly, you can share to another receiver (gmail should work fine) and than copy-paste to Dropbox.
I'm sorry if this procedure is not ideal for you.
Lastly, you can backup the history files from the storage of your phone. The history files are located in
/storage/emulated/(storage)/Android/data/org.digitalillusion.droid.iching/files with the name of history-(name you gave).bin
You can copy these files to a new installation (for instance on another phone) and find all the contents you originally produced.
I hope this helps, sorry for not replying sooner, there may be some issue in the email forward

**Comment by Inclement9** [comment]
Thanks for the information!

> Hi, please make sure that in the settings you have selected Content to share: Reading. 

Yes, it already was set to that.

> The share feature produces some HTML content; I have no control on how the receiver (Dropbox app in your case) handle this content. 

It didn't work. Here's what happened:
• I opened one of my readings.
• Tapped the "Share using...Add to Dropbox" button.
• The screen flashed.
• It went back to the reading screen and displayed the message, "Sorry, an error occurred. Please try again later."

I tried it a couple more times; same result.

> If it doesn't work directly, you can share to another receiver (gmail should work fine) 

This didn't work, but I don't think it has anything to do with you. Here's what happened:

I was able to set up my Outlook.com account on my tablet in the sense that the tablet's native email app accepted my login information and I could see my emails that it synced. But it was hilariously unusable. Everything kept fluttering up and down on on the screen.

I could see my reading in the email app's Outbox, but there was a message "Sending failed. Pull down this list to try again, or tap on an individual message to get more information. (Outlook)" 

Pulling and tapping did nothing. At this point I gave up and deleted my Outlook account from the tablet.

> Lastly, you can backup the history files from the storage of your phone. The history files are located in /storage/emulated/(storage)/Android/data/org.digitalillusion.droid.iching/files with the name of history-(name you gave).bin 

This didn't work, either. 

I accessed the tablet's storage on my laptop. The actual path is _slightly_ different:
`This PC\Fire\Internal storage\Android\data\org.digitalillusion.droid.iching\files`
The folder showed as empty - no .bin file.

(If it matters, I do have Windows set to show hidden files.)

**Comment by Inclement9** [comment]
Update

I finally got this to work with the Google Drive Android app.

**Comment by digitalillusion** [comment]
version 1.11.0 has a backup/recovery feature accessible through settings menu
